Web Programlama_VİZE/BeyzanurDuzceEduTr/Controllers/AdminController.cs
using BeyzanurDuzceEduTr.Controllers.Utility;
using BeyzanurDuzceEduTr.Models;
using BeyzanurDuzceEduTr.Models.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BeyzanurDuzceEduTr.Controllers
{
    [CustomHttpsOnlyFilter]
    public class AdminController : Controller
    {
        private BeyzanurDuzceEduTrContext _ctx;
        public AdminController(BeyzanurDuzceEduTrContext context)
        {
            _ctx = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Announcements()
        {
            return View("Announcement", _ctx.Announcements.ToList());
        }
        public IActionResult Users()
        {
            return View("User", _ctx.Users.ToList());
        }

        public ActionResult GetUser(string UserId)
        {
            //Users model = _ctx.Users.Where(x => x.Id == UserId).First();

            //LINQ SORGUSU
            var data = (from a in _ctx.Users
                        where a.Id == UserId
                        select a);

            return PartialView("PV_updateUserView", data.First());
        }


        public JsonResult AddUser(Users model)
        {
            var result = new { statu = "", message = "" };
            try
            {
                model.PasswordHash = Utility.Utility.MD5eDonustur(model.PasswordHash);
                model.CreateDate = DateTime.Now;
                model.NormalizedUserName = model.UserName;
                model.NormalizedEmail= model.Email;
                _ctx.Users.Add(model);
                _ctx.SaveChanges();
                result = new { statu = "ok", message = "Kullanıcı oluşturuldu" };
            }
            catch (Exception ex)
            {
                result = new { statu = "fail", message = ex.Message };
            }

            return Json(result);
        }
        public JsonResult UpdateUser(Users model)
        {
            var result = new { statu = "", message = "" };
            try
            {
                model.NormalizedUserName = model.UserName;
                model.NormalizedEmail = model.Email;
                _ctx.Entry(model).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                _ctx.SaveChanges();
                result = new { statu = "ok", message = "Kullanıcı güncellendi." };
            }
            catch (Exception ex)
            {
                result = new { statu = "fail", message = ex.Message };
            }

            return Json(result);
        }
        public JsonResult DeleteUser(Users model)
        {
            var result = new { statu = "", message = "" };
            try
            {
                Users u = _ctx.Users.Find(model.Id);
                _ctx.Entry(u).State = Microsoft.EntityFrameworkCore.EntityState.Deleted;
                _ctx.SaveChanges();
                result = new { statu = "ok", message = "Kullanıcı silindi" };
            }
            catch (Exception ex)
            {
                result = new { statu = "fail", message = ex.Message };
            }

            return Json(result);
        }
        public JsonResult AddAnnouncement(Announcement model)
        {
            var result = new { statu = "", message = "" };
            try
            {
                model.CreateDate = DateTime.Now;
                _ctx.Announcements.Add(model);
                _ctx.SaveChanges();
                result = new { statu = "ok", message = "Duyuru oluşturuldu" };
            }
            catch (Exception ex)
            {
                result = new { statu = "fail", message = ex.Message };
            }

            return Json(result);
        }
        public JsonResult DeleteAnnouncement(Announcement model)
        {
            var result = new { statu = "", message = "" };
            try
            {
                Announcement u = _ctx.Announcements.Find(model.AnnouncementId);
                _ctx.Entry(u).State = Microsoft.EntityFrameworkCore.EntityState.Deleted;
                _ctx.SaveChanges();
                result = new { statu = "ok", message = "Duyuru silindi" };
            }
            catch (Exception ex)
            {
                result = new { statu = "fail", message = ex.Message };
            }

            return Json(result);
        }
        public ActionResult GetAnnouncement(int AnnouncementId)
        {
            Announcement model = _ctx.Announcements.Find(AnnouncementId);
            return PartialView("PV_AnnouncementUpdate", model);
        }
        public JsonResult UpdateAnnouncement(Announcement model)
        {
            var result = new { statu = "", message = "" };
            try
            {
                _ctx.Entry(model).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                _ctx.SaveChanges();
                result = new { statu = "ok", message = "Duyuru güncellendi." };
            }
            catch (Exception ex)
            {
                result = new { statu = "fail", message = ex.Message };
            }

            return Json(result);
        }
    }
}

Web Programlama_VİZE/BeyzanurDuzceEduTr/Controllers/AuthenticationController.cs
using BeyzanurDuzceEduTr.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Authorization;
using BeyzanurDuzceEduTr.Models.Entities;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;

namespace BeyzanurDuzceEduTr.Controllers
{
    [AllowAnonymous]
    public class AuthenticationController : Controller
    {
        private BeyzanurDuzceEduTrContext _ctx;
        private SignInManager<Users> _signInManager;
        private UserManager<Users> _usermanager;

        public AuthenticationController(BeyzanurDuzceEduTrContext context, UserManager<Users> userManager, SignInManager<Users> signInManager)
        {
            _ctx = context;
            _signInManager = signInManager;
            _usermanager = userManager;
        }
        //Functons
        [HttpPost]
        public async Task<JsonResult> Login(string userId, string password)
        {
            var result = new { statu = "", message = "" };
            string Pwd = Utility.Utility.MD5eDonustur(password);
            var user = await _usermanager.FindByNameAsync(userId);
            
            if (user.UserName == userId && user.PasswordHash == Pwd)
            {
                result = new { statu = "ok", message = "" };
                Utility.Utility.isLogin = true;
                var sonuc = await _signInManager.PasswordSignInAsync(user.UserName, user.PasswordHash, true, false);
            }

            return Json(result);
        }
    }
}

Web Programlama_VİZE/BeyzanurDuzceEduTr/Views/Admin/Shared/_Layout.cshtml
<!doctype html>
<html lang="en" data-layout="vertical" data-topbar="light" data-sidebar="dark" data-sidebar-size="lg">
<head>
    @Html.Partial("~/Views/Admin/Shared/_title_meta.cshtml")
    @RenderSection("styles", required: false)
    @Html.Partial("~/Views/Admin/Shared/_head_css.cshtml")
</head>
<body>
    <!-- Begin page -->
    <div id="layout-wrapper">
        @Html.Partial("~/Views/Admin/Shared/_menu.cshtml")

        <!-- ============================================================== -->
        <!-- Start right Content here -->
        <!-- ============================================================== -->
        <div class="main-content">

            <div class="page-content">
                <div class="container-fluid">
                    @Html.Partial("~/Views/Admin/Shared/_page_title.cshtml")

                    @RenderBody()
                </div>
            </div>
            @Html.Partial("~/Views/Admin/Shared/_footer.cshtml")
        </div>

    </div>
    <!-- END layout-wrapper -->
    @*@Html.Partial("~/Views/Admin/Shared/_customizer.cshtml")*@

    @Html.Partial("~/Views/Admin/Shared/_vendor_scripts.cshtml")

    @RenderSection("scripts", required: false)
</body>
</html>

Web Programlama_VİZE/BeyzanurDuzceEduTr/Views/Admin/Shared/_footer.cshtml
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                <script>document.write(new Date().getFullYear())</script> © Velzon.
            </div>
            <div class="col-sm-6">
                <div class="text-sm-end d-none d-sm-block">
                    Design & Develop by Themesbrand
                </div>
            </div>
        </div>
    </div>
</footer>

Web Programlama_VİZE/BeyzanurDuzceEduTr/Views/Admin/Shared/_head_css.cshtml
<!-- Layout config Js -->
<script src="~/Content/assets/js/layout.js"></script>
<!-- Bootstrap Css -->
<link href="~/Content/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<!-- Icons Css -->
<link href="~/Content/assets/css/icons.min.css" rel="stylesheet" type="text/css" />
<!-- App Css-->
<link href="~/Content/assets/css/app.min.css" rel="stylesheet" type="text/css" />
<!-- custom Css-->
<link href="~/Content/assets/css/custom.min.css" rel="stylesheet" type="text/css" />

Web Programlama_VİZE/BeyzanurDuzceEduTr/Views/Admin/Shared/_menu.cshtml
@Html.Partial("~/Views/Admin/Shared/_topbar.cshtml")
@Html.Partial("~/Views/Admin/Shared/_sidebar.cshtml")

Web Programlama_VİZE/BeyzanurDuzceEduTr/Views/Admin/Shared/_page_title.cshtml
<!-- start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box d-sm-flex align-items-center justify-content-between">
            <h4 class="mb-sm-0">@ViewBag.ptitle</h4>

            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="javascript: void(0);">@ViewBag.pagetitle</a></li>
                    <li class="breadcrumb-item active">@ViewBag.ptitle</li>
                </ol>
            </div>

        </div>
    </div>
</div>
<!-- end page title -->

Web Programlama_VİZE/BeyzanurDuzceEduTr/Views/Admin/Shared/_sidebar.cshtml
<!-- ========== App Menu ========== -->
<div class="app-menu navbar-menu">
    <!-- LOGO -->
    <div class="navbar-brand-box">
        <!-- Dark Logo-->
        <a href="@Url.Action("Index", "Admin")" class="logo logo-dark">
            <span class="logo-sm">
                <img src="~/Content/img/logo.PNG" alt="" height="50">
            </span>
            <span class="logo-lg">
                <img src="~/Content/img/logo.PNG" alt="" height="50">
            </span>
        </a>
        <!-- Light Logo-->
        <a href="@Url.Action("Index", "Admin")" class="logo logo-light">
            <span class="logo-sm">
                <img src="~/Content/img/logo.PNG" alt="" height="50">
            </span>
            <span class="logo-lg">
                <img src="~/Content/img/logo.PNG" alt="" height="50">
            </span>
        </a>
        <button type="button" class="btn btn-sm p-0 fs-20 header-item float-end btn-vertical-sm-hover" id="vertical-hover">
            <i class="ri-record-circle-line"></i>
        </button>
    </div>

    <div id="scrollbar">
        <div class="container-fluid">

            <div id="two-column-menu">
            </div>
            <ul class="navbar-nav" id="navbar-nav">
                <li class="menu-title"><span data-key="t-menu">Menu</span></li>
                <li class="nav-item">
                    <a href="@Url.Action("Index", "Home")" class="nav-link" data-key="t-analytics"> Websitesine Dön </a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Announcements", "Admin")" class="nav-link" data-key="t-analytics"> Duyuru İşlemleri </a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Users", "Admin")" class="nav-link" data-key="t-crm"> Kullanıcı İşlemleri </a>
                </li>
                @*<li class="nav-item">
            <a href="@Url.Action("Logout", "Authentication")" class="nav-link" data-key="t-analytics">Çıkış Yap </a>
        </li>*@

            </ul>
        </div>
        <!-- Sidebar -->
    </div>
</div>
<!-- Left Sidebar End -->
<!-- Vertical Overlay-->
<div class="vertical-overlay"></div>

Web Programlama_VİZE/BeyzanurDuzceEduTr/Views/Admin/Shared/_title_meta.cshtml
<meta charset="utf-8" />
<title>@ViewBag.title</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
<meta content="Themesbrand" name="author" />
<!-- App favicon -->
<link rel="shortcut icon" href="~/Content/assets/images/favicon.ico">

Web Programlama_VİZE/BeyzanurDuzceEduTr/Views/Admin/Shared/_topbar.cshtml
<header id="page-topbar">
    <div class="layout-width">
        <div class="navbar-header">
            <div class="d-flex">
                <!-- LOGO -->
                <div class="navbar-brand-box horizontal-logo">
                    <a href="@Url.Action("Index", "Dashboard")" class="logo logo-dark">
                        <span class="logo-sm">
                            <img src="~/assets/images/logo-sm.png" alt="" height="22">
                        </span>
                        <span class="logo-lg">
                            <img src="~/assets/images/logo-dark.png" alt="" height="17">
                        </span>
                    </a>

                    <a href="@Url.Action("Index", "Dashboard")" class="logo logo-light">
                        <span class="logo-sm">
                            <img src="~/assets/images/logo-sm.png" alt="" height="22">
                        </span>
                        <span class="logo-lg">
                            <img src="~/assets/images/logo-light.png" alt="" height="17">
                        </span>
                    </a>
                </div>

                <button type="button" class="btn btn-sm px-3 fs-16 header-item vertical-menu-btn topnav-hamburger"
                    id="topnav-hamburger-icon">
                    <span class="hamburger-icon">
                        <span></span>
                        <span></span>
                        <span></span>
                    </span>
                </button>

                <!-- App Search-->
                <form class="app-search d-none d-md-block">
                    <div class="position-relative">
                        <input type="text" class="form-control" placeholder="Search..." autocomplete="off"
                            id="search-options" value="">
                        <span class="mdi mdi-magnify search-widget-icon"></span>
                        <span class="mdi mdi-close-circle search-widget-icon search-widget-icon-close d-none"
                            id="search-close-options"></span>
                    </div>
                    <div class="dropdown-menu dropdown-menu-lg" id="search-dropdown">
                        <div data-simplebar style="max-height: 320px;">
                            <!-- item-->
                            <div class="dropdown-header">
                                <h6 class="text-overflow text-muted mb-0 text-uppercase">Recent Searches</h6>
                            </div>

                            <div class="dropdown-item bg-transparent text-wrap">
                                <a href="@Url.Action("Index", "Dashboard")" class="btn btn-soft-secondary btn-sm btn-rounded">how to setup <i
                                        class="mdi mdi-magnify ms-1"></i></a>
                                <a href="@Url.Action("Index", "Dashboard")" class="btn btn-soft-secondary btn-sm btn-rounded">buttons <i
                                        class="mdi mdi-magnify ms-1"></i></a>
                            </div>
                            <!-- item-->
                            <div class="dropdown-header mt-2">
                                <h6 class="text-overflow text-muted mb-1 text-uppercase">Pages</h6>
                            </div>

                            <!-- item-->
                            <a href="javascript:void(0);" class="dropdown-item notify-item">
                                <i class="ri-bubble-chart-line align-middle fs-18 text-muted me-2"></i>
                                <span>Analytics Dashboard</span>
                            </a>

                            <!-- item-->
                            <a href="javascript:void(0);" class="dropdown-item notify-item">
                                <i class="ri-lifebuoy-line align-middle fs-18 text-muted me-2"></i>
                                <span>Help Center</span>
                            </a>

                            <!-- item-->
                            <a href="javascript:void(0);" class="dropdown-item notify-item">
                                <i class="ri-user-settings-line align-middle fs-18 text-muted me-2"></i>
                                <span>My account settings</span>
                            </a>

                            <!-- item-->
                            <div class="dropdown-header mt-2">
                                <h6 class="text-overflow text-muted mb-2 text-uppercase">Members</h6>
                            </div>

                            <div class="notification-list">
                                <!-- item -->
                                <a href="javascript:void(0);" class="dropdown-item notify-item py-2">
                                    <div class="d-flex">
                                        <img src="~/assets/images/users/avatar-2.jpg"
                                            class="me-3 rounded-circle avatar-xs" alt="user-pic">
                                        <div class="flex-1">
                                            <h6 class="m-0">Angela Bernier</h6>
                                            <span class="fs-11 mb-0 text-muted">Manager</span>
                                        </div>
                                    </div>
                                </a>
                                <!-- item -->
                                <a href="javascript:void(0);" class="dropdown-item notify-item py-2">
                                    <div class="d-flex">
                                        <img src="~/assets/images/users/avatar-3.jpg"
                                            class="me-3 rounded-circle avatar-xs" alt="user-pic">
                                        <div class="flex-1">
                                            <h6 class="m-0">David Grasso</h6>
                                            <span class="fs-11 mb-0 text-muted">Web Designer</span>
                                        </div>
                                    </div>
                                </a>
                                <!-- item -->
                                <a href="javascript:void(0);" class="dropdown-item notify-item py-2">
                                    <div class="d-flex">
                                        <img src="~/assets/images/users/avatar-5.jpg"
                                            class="me-3 rounded-circle avatar-xs" alt="user-pic">
                                        <div class="flex-1">
                                            <h6 class="m-0">Mike Bunch</h6>
                                            <span class="fs-11 mb-0 text-muted">React Developer</span>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>

                        <div class="text-center pt-3 pb-1">
                            <a href="@Url.Action("SearchResults", "Pages")" class="btn btn-primary btn-sm">View All Results <i
                                    class="ri-arrow-right-line ms-1"></i></a>
                        </div>
                    </div>
                </form>
            </div>

        </div>
    </div>
</header>

Web Programlama_VİZE/BeyzanurDuzceEduTr/Views/Admin/Shared/_vendor_scripts.cshtml
<!-- JAVASCRIPT -->
<script src="~/Content/assets/libs/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/Content/assets/libs/simplebar/simplebar.min.js"></script>
<script src="~/Content/assets/libs/node-waves/waves.min.js"></script>
<script src="~/Content/assets/libs/feather-icons/feather.min.js"></script>
<script src="~/Content/assets/js/pages/plugins/lord-icon-2.1.0.js"></script>
<script src="~/Content/assets/js/plugins.js"></script>